name: Compress soul.c to Binary

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install UPX
        run: sudo apt-get update -y && sudo apt-get upgrade -y
             sudo apt-get install -y upx gcc
      
      - name: Compile & Compress soul.c
        run: |
          mkdir -p binaries
          gcc soul.c -o binaries/soul
          upx --best binaries/soul
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: soul-binary
          path: binaries/soul
